!#/bin/bash
wget -P plugins https://compedu.stanford.edu/karel-reader/docs/plugins/jquery.min.js
wget -P plugins/bootstrap/css https://compedu.stanford.edu/karel-reader/docs/plugins/bootstrap/css/bootstrap.min.css
wget -P plugins/bootstrap/js https://compedu.stanford.edu/karel-reader/docs/plugins/bootstrap/js/bootstrap.min.js
wget -P plugins/bootstrap/fonts https://compedu.stanford.edu/karel-reader/docs/plugins/bootstrap/fonts/glyphicons-halflings-regular.woff2 
wget -P plugins/bootstrap/fonts https://compedu.stanford.edu/karel-reader/docs/plugins/bootstrap/fonts/glyphicons-halflings-regular.woff 
wget https://compedu.stanford.edu/karel-reader/docs/style.css
wget -P karel/js/html https://compedu.stanford.edu/karel-reader/docs/karel/js/html/websiteImports.js
wget -P karel/lib https://compedu.stanford.edu/karel-reader/docs/karel/lib/jquery.js
wget -P karel/lib https://compedu.stanford.edu/karel-reader/docs/karel/lib/browser_detect.js
wget -P karel/lib https://compedu.stanford.edu/karel-reader/docs/karel/lib/util.js
wget -P karel/lib https://compedu.stanford.edu/karel-reader/docs/karel/lib/tabs.js
wget -P karel/codeMirror https://compedu.stanford.edu/karel-reader/docs/karel/codeMirror/js/codemirror.js
wget -P karel/ace https://compedu.stanford.edu/karel-reader/docs/karel/ace/ace.js
wget -P karel/ace https://compedu.stanford.edu/karel-reader/docs/karel/ace/theme-eclipse.js
wget -P karel/ace https://compedu.stanford.edu/karel-reader/docs/karel/ace/mode-javascript.js
wget -P karel/ace https://compedu.stanford.edu/karel-reader/docs/karel/ace/mode-java.js
wget -P karel/ace https://compedu.stanford.edu/karel-reader/docs/karel/ace/mode-python.js
wget -P karel/lib https://compedu.stanford.edu/karel-reader/docs/karel/lib/curvycorners.js
wget -P karel/lib https://compedu.stanford.edu/karel-reader/docs/karel/lib/jquery.js
wget -P karel/boxy https://compedu.stanford.edu/karel-reader/docs/karel/boxy/jquery.boxy.js
wget -P karel/lib https://compedu.stanford.edu/karel-reader/docs/karel/lib/swal.min.js
wget -P karel/js/ide https://compedu.stanford.edu/karel-reader/docs/karel/js/ide/karelImages.js
wget -P karel/js/ide https://compedu.stanford.edu/karel-reader/docs/karel/js/ide/karelSingleton.js
wget -P karel/js/ide https://compedu.stanford.edu/karel-reader/docs/karel/js/ide/karelConstants.js
wget -P karel/js/ide https://compedu.stanford.edu/karel-reader/docs/karel/js/ide/action.js
wget -P karel/js/ide https://compedu.stanford.edu/karel-reader/docs/karel/js/ide/beepers.js
wget -P karel/js/ide https://compedu.stanford.edu/karel-reader/docs/karel/js/ide/walls.js
wget -P karel/js/ide https://compedu.stanford.edu/karel-reader/docs/karel/js/ide/squareColors.js
wget -P karel/js/ide https://compedu.stanford.edu/karel-reader/docs/karel/js/ide/canvasModel.js
wget -P karel/js/ide https://compedu.stanford.edu/karel-reader/docs/karel/js/ide/karelModel.js
wget -P karel/js/ide https://compedu.stanford.edu/karel-reader/docs/karel/js/ide/karelView.js
wget -P karel/js/ide https://compedu.stanford.edu/karel-reader/docs/karel/js/ide/karel.js
wget -P karel/js/ide https://compedu.stanford.edu/karel-reader/docs/karel/js/ide/karelCompiledEngine.js
wget -P karel/js/ide https://compedu.stanford.edu/karel-reader/docs/karel/js/ide/karelEvalEngine.js
wget -P karel/js/ide https://compedu.stanford.edu/karel-reader/docs/karel/js/ide/karelIde.js
wget -P karel/js/html https://compedu.stanford.edu/karel-reader/docs/karel/js/html/starterCode.js
wget -P karel/js/api/java https://compedu.stanford.edu/karel-reader/docs/karel/js/api/java/en.json
wget -P karel/js/compiler https://compedu.stanford.edu/karel-reader/docs/karel/js/compiler/karelJavaCompiler.js
wget -P karel/js/compiler https://compedu.stanford.edu/karel-reader/docs/karel/js/compiler/karelPythonCompiler.js
wget -P karel/js/compiler/scanner https://compedu.stanford.edu/karel-reader/docs/karel/js/compiler/scanner/TokenScanner.js
wget -P karel/js/compiler/parser https://compedu.stanford.edu/karel-reader/docs/karel/js/compiler/parser/Parser.js
wget -P karel/js/compiler/parser https://compedu.stanford.edu/karel-reader/docs/karel/js/compiler/parser/XParser.js
wget -P karel/js/compiler/vm https://compedu.stanford.edu/karel-reader/docs/karel/js/compiler/vm/VM.js
wget -P karel/js/compiler/vm https://compedu.stanford.edu/karel-reader/docs/karel/js/compiler/vm/XVM.js
wget -P karel/js/compiler/karel https://compedu.stanford.edu/karel-reader/docs/karel/js/compiler/karel/KarelParser.js
wget -P karel/js/compiler/karel https://compedu.stanford.edu/karel-reader/docs/karel/js/compiler/karel/KarelPythonParser.js
wget -P karel/js/compiler/karel https://compedu.stanford.edu/karel-reader/docs/karel/js/compiler/karel/KarelVM.js
wget -P karel/js/dialog https://compedu.stanford.edu/karel-reader/docs/karel/js/dialog/referenceDialog.js
wget -P karel/js/dialog https://compedu.stanford.edu/karel-reader/docs/karel/js/dialog/deployDialog.js
wget -P karel/css https://compedu.stanford.edu/karel-reader/docs/karel/css/style.css
wget -P karel/boxy/stylesheets https://compedu.stanford.edu/karel-reader/docs/karel/boxy/stylesheets/boxy.css
wget -P karel/images https://compedu.stanford.edu/karel-reader/docs/karel/images/karelNorth.png
wget -P karel/images https://compedu.stanford.edu/karel-reader/docs/karel/images/karelSouth.png
wget -P karel/js/api/python https://compedu.stanford.edu/karel-reader/docs/karel/js/api/python/en.json 
wget -P karel/images https://compedu.stanford.edu/karel-reader/docs/karel/images/karelEast.png 
wget -P karel/images https://compedu.stanford.edu/karel-reader/docs/karel/images/karelWest.png
wget -P karel/images https://compedu.stanford.edu/karel-reader/docs/karel/images/beeper.jpg
wget -P karel/images https://compedu.stanford.edu/karel-reader/docs/karel/images/cross.png
wget -P karel/images https://compedu.stanford.edu/karel-reader/docs/karel/images/karelSouthSmall.png
wget -P karel/images https://compedu.stanford.edu/karel-reader/docs/karel/images/karelNorthSmall.png
wget -P karel/images https://compedu.stanford.edu/karel-reader/docs/karel/images/karelEastSmall.png
wget -P karel/images https://compedu.stanford.edu/karel-reader/docs/karel/images/karelWestSmall.png
wget -P karel/images https://compedu.stanford.edu/karel-reader/docs/karel/images/karelNorthTiny.png
wget -P karel/images https://compedu.stanford.edu/karel-reader/docs/karel/images/karelSouthTiny.png
wget -P karel/images https://compedu.stanford.edu/karel-reader/docs/karel/images/karelEastTiny.png
wget -P karel/images https://compedu.stanford.edu/karel-reader/docs/karel/images/karelWestTiny.png
wget -P karel/worlds https://compedu.stanford.edu/karel-reader/docs/karel/worlds/1x1.w
wget -P karel/worlds https://compedu.stanford.edu/karel-reader/docs/karel/worlds/4x4.w
wget -P karel/worlds https://compedu.stanford.edu/karel-reader/docs/karel/worlds/3x6.w
wget -P karel/worlds https://compedu.stanford.edu/karel-reader/docs/karel/worlds/7x7.w
wget -P karel/worlds https://compedu.stanford.edu/karel-reader/docs/karel/worlds/8x8.w
wget -P karel/worlds https://compedu.stanford.edu/karel-reader/docs/karel/worlds/commands.w
wget -P karel/worlds https://compedu.stanford.edu/karel-reader/docs/karel/worlds/commandsGoal.w
wget -P karel/worlds https://compedu.stanford.edu/karel-reader/docs/karel/worlds/stepUpM1.w
wget -P karel/worlds https://compedu.stanford.edu/karel-reader/docs/karel/worlds/stepUpGoal.w
wget -P karel/worlds https://compedu.stanford.edu/karel-reader/docs/karel/worlds/stepUpM2.w
wget -P karel/worlds https://compedu.stanford.edu/karel-reader/docs/karel/worlds/stepUp.w
wget -P karel/worlds https://compedu.stanford.edu/karel-reader/docs/karel/worlds/pothole.w
wget -P karel/worlds https://compedu.stanford.edu/karel-reader/docs/karel/worlds/potholeGoal.w
wget -P karel/worlds https://compedu.stanford.edu/karel-reader/docs/karel/worlds/99beepersStart.w
wget -P karel/worlds https://compedu.stanford.edu/karel-reader/docs/karel/worlds/99beepersGoal.w
wget -P karel/worlds https://compedu.stanford.edu/karel-reader/docs/karel/worlds/cornerBeepersStart.w
wget -P karel/worlds https://compedu.stanford.edu/karel-reader/docs/karel/worlds/invert.w
wget -P karel/worlds https://compedu.stanford.edu/karel-reader/docs/karel/worlds/beeperTowers.w
wget -P karel/worlds https://compedu.stanford.edu/karel-reader/docs/karel/worlds/beeperTowersGoal.w
wget -P karel/codeMirror/js https://compedu.stanford.edu/karel-reader/docs/karel/codeMirror/js/codemirror.js 